# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: open-shared-network
ko_fi: opensharednetwork
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: OpenSharedNetwork
otechie: # Replace with a single Otechie username
lfx_crowdfunding: a8f73595-0093-44fa-9c5d-c2de6ed20a0b
custom:  ['link1', 'link2']
